### ISSUE TITLE
Error file_put_contents when trying to add-token in Alfred 3

### ISSUE THREAD

**Issue by Tovrik** [yannickglt/alfred-slack#15]
This is relatively simple to solve and I just wanted to put this here for anyone else who might run across it. 

1. Open /Users/username/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.22EEC29C-B28B-40A5-B234-FFB52703D649/scripts/libs/Workflows.php 
2. There is a line (a file path) in the file which refers to Alfred 2 instead of Alfred 3, just change that and everything works perfectly.

**Comment by whalesingswee** [comment]
Thanks for this! Very helpful. Hope Author update this one

**Comment by jingxinxin** [comment]
Thanks for this! It works.

**Comment by thatsecuritydude** [comment]
This still doesn't work. I continue to see debug logs trying to access Alfred 2 folders that end up failing. I tried deleting that user.workflow.<guid> folder and reinstalling the tool, but that didn't help either. Any other suggestions for this would be great. Thanks.

**Comment by yannickglt** [comment]
Hi! The version 3 of the workflow was just released (it includes the new Slack OAUTH implementation as the previous one is deprecated). Your issue should be fixed as well.
If not, feel free to let me know and I will give it a check quickly.
