### ISSUE TITLE
Invalid OAUTH unique code. Please check the generated unique code.

### ISSUE THREAD

**Issue by xilopaint** [yannickglt/alfred-slack#24]
What's going on?

**Comment by yannickglt** [comment]
What's the length of your unique code?

**Comment by xilopaint** [comment]
116 chars.

**Comment by yannickglt** [comment]
OK. I published a new version without checking the OAUTH code length as it does not look to be relevant. Just update it 😉

**Comment by xilopaint** [comment]
It worked. Thank you!

**Comment by yannickglt** [comment]
You're welcome. I hope you'll enjoy the workflow!
