### ISSUE TITLE
Readme.md not informative enough.

### ISSUE THREAD

**Issue by drewswaycool** [yannickglt/alfred-slack#27]
Step 4 provides no context for:

>4. Launch the slack workflow with the parameter....

i.e. how? where?

**Comment by yannickglt** [comment]
As you would do with any other Alfred command: pressing `cmd+space` (depending on the shortcut you chose) and typing `slack --add-client UNIQUE_CODE:CLIENT_SECRET`. The unique code and the client secret come from the previous steps.
