### ISSUE TITLE
Cannot jump to 'you'

### ISSUE THREAD

**Issue by orf** [yannickglt/alfred-slack#28]
Slack has a great 'you' direct messages, where you can write notes and send messages to yourself. You can't seem to jump to this channel, if you do `slack you` or `slack [your_name]` it doesn't autocomplete.

Is this by design, or am I making a mistake in the search query?

Edit: Also thank you a lot for this workflow, it's very useful 👍 ❤️

**Comment by yannickglt** [comment]
Glad you enjoy it 😊 
It looks like the channel for `yourself` is named `@slackbot` as well 😕 ... You must have two entries named `@slackboot`, one for the "real" slackbot and another one for yourself (with your picture as icon).
It's something related to the Slack API, but I'll take a look to know if it's something catchable by the workflow and display a more relevant label.

**Comment by yannickglt** [comment]
It should be fixed in v3.2.0
