### ISSUE TITLE
Bring the app on top

### ISSUE THREAD

**Issue by fbourbonnais** [yannickglt/alfred-slack#3]
When the Slack's window is closed, the Slack command doesn't bring the Slack window on top.

**Comment by tamano** [comment]
Same for me.
I'm using  Alfred 2.8(414) / OS X 10.10.5 / Slack 1.1.7 (3010)

**Comment by yannickglt** [comment]
Thanks for your returns guys. I am going to see what is possible as, for the moment, I just use the Slack URL scheme provided by Slack itself.

**Comment by yannickglt** [comment]
Fixed by https://github.com/yannickglt/alfred-slack/commit/3e8b4131b313325dbcd6b9498f7b6404fbdd0aa2

**Comment by tamano** [comment]
Thank you. Now I see it working perfectly ;-)

**Comment by yannickglt** [comment]
Thanks to you! And sorry for the inconvenience ;)
