### ISSUE TITLE
Fatal error allocating memory on refresh

### ISSUE THREAD

**Issue by rtgoodwin** [yannickglt/alfred-slack#31]
Thanks for making this! I can't seem to get going though. After getting the client successfully added, the refresh fails with a fatal error. I tried clearing the data and trying again, but no dice. Log below:

`ACTION: AlfredSlack\Controllers\ConfigController::refreshCacheAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"refreshCache\",\"params\":[]}";include "scripts/index.php";';
Auth refreshed for team XXXXX
Channels refreshed for team XXXXX
Groups refreshed for team XXXX
[2018-02-26 11:13:04][action.script] Processing output of 'output.notification' with arg '
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 18312808 bytes) in /Users/XXXXX/Dropbox/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.DE22DD6E-E4F1-44B5-9532-BD453966CA8B/scripts/libs/Workflows.php on line 410
`
Any ideas? Alfred 3.6. 

Thanks!!

**Comment by rtgoodwin** [comment]
Well, I temporarily fixed it by removing the memory limit for php systemwide (php.ini). Not ideal, but it seems to get the job done...as it's still refreshing. (This instance has many thousands of users.) I don't know if there's a way to maybe use markers or paging to iterate through the caching process vs "one pass"?

**Comment by yannickglt** [comment]
It's quiet hard to reproduce as I'm not a member of such a large team. However I tried to improve the cache process. Maybe you'll be able to make a refresh without failing.

**Comment by yannickglt** [comment]
Closed of inactivity.
