### ISSUE TITLE
Feat Req: Ability to set status

### ISSUE THREAD

**Issue by thonydam** [yannickglt/alfred-slack#36]
Hi!

Thanks for building this super Alfred workflow!

Could we add the capability to set a custom status from Alfred?

Thanks!

**Comment by yannickglt** [comment]
Hey!
Thanks for your using the Slack workflow for Alfred and for your suggestion. 
You'll be happy to learn that the version 4 of the workflow now handles custom statuses. For the moment, only the Slack's predefined statuses can be selected but it's a good start I think.
