### ISSUE TITLE
Add scopes list to README.md

### ISSUE THREAD

**Issue by antonio-ramadas** [yannickglt/alfred-slack#38]
First of all, great job. This is really useful! I just have this minor suggestion of improvement.

When setting up the app, there could be more screenshots showing the addition of scopes. The list is [quite extensive](https://github.com/yannickglt/alfred-slack/blob/gh-pages/assets/script.js#L4-L23) and is not easily shown to the user (I had to dive in into the source code). Adding at least one screenshot mentioning the necessary steps would be useful :)

**Comment by yannickglt** [comment]
Hi, 
Thank you for using the Slack workflow for Alfred!
I added some steps and screenshots to the readme in b75eb617e1853b73e355a1fbc331cdc8be885f45, hopefully it will be easier to understand.
