### ISSUE TITLE
More like a question than an issue

### ISSUE THREAD

**Issue by bridgestew** [yannickglt/alfred-slack#4]
Does the Slack workflow assume you only belong to one Slack Team? I have gotten tokens for different teams in which I would have wanted to use this workflow, but it only seems to work with the first one. I can't tell if I'm doing something wrong or if it was only meant to work with one.

Thanks!

**Comment by yannickglt** [comment]
Yes you are right, the worklow assumes you work with only one team at once. But if there is a real interest working with several teams, it may be an improvement I guess.

**Comment by bridgestew** [comment]
Thanks for the response! It's not necessary that this do more than you designed it for. I don't know how widespread Slack is used for multiple teams. I happen to be one of those people. At least I know I'm not just using it incorrectly. :)

**Comment by altern8tif** [comment]
Multiple-team support is definitely welcomed!  Thanks for the workflow anyway :smile:

**Comment by yannickglt** [comment]
Ahah! Glad to announce that the dev is already in progress :smile:

**Comment by altern8tif** [comment]
:+1:

**Comment by yannickglt** [comment]
Pleased to inform you that multi-team is now supported! You can update your workflow to 2.2.0 and add another token to your the flow.
