### ISSUE TITLE
fall back to command list if channel name typed contains consecutive "-"

### ISSUE THREAD

**Issue by hiroxy** [yannickglt/alfred-slack#42]
Hi,
The workflow will fail to list a channel name containing consecutive "-" when it is typed.
If the channel name is, for example, `#channel-012`, commands such as `--add-client` and `--mark` will be listed when `slack #channel--` is typed.

**Comment by yannickglt** [comment]
Hi,
It should be fixed with the last version.

**Comment by hiroxy** [comment]
Hi, 
Thank you for fixing quickly. I've confirmed that the issue was solved using the latest one.

**Comment by yannickglt** [comment]
Thanks for feedback
