### ISSUE TITLE
bad_redirect_uri

### ISSUE THREAD

**Issue by joaomneto** [yannickglt/alfred-slack#44]
Hi!

I'm getting a bad_redirect_uri error when adding the client.

These are the redirect urls I've configured:

![image](https://user-images.githubusercontent.com/5557570/48352635-20323400-e685-11e8-8c7b-a62148a94bed.png)

Am I doing something wrong? 

Thanks!

**Comment by yannickglt** [comment]
Hi,
The redirect URLs sound good. When does the error appear?

**Comment by yannickglt** [comment]
Close for inactivity.
