### ISSUE TITLE
OAuth Error: Invalid client_id parameter

### ISSUE THREAD

**Issue by dwillitzer** [yannickglt/alfred-slack#45]
Filling out required information https://yannickglt.github.io/alfred-slack/ slack returns `OAuth Error: Invalid client_id parameter`. I have double checked everything is correct, but still can't proceed. Please advise?

**Comment by yannickglt** [comment]
What's your team name? Does it contain special characters?

**Comment by dwillitzer** [comment]
No. All alphabetical characters a-z

**Comment by dwillitzer** [comment]
CanopyDigital

**Comment by yannickglt** [comment]
Could you copy the URL of the page displaying this error?

**Comment by dwillitzer** [comment]
error `OAuth Error: Invalid client_id parameter`

decoded-url
```
https://slack.com/oauth/authorize?client_id=‪‬5200166808.540275786487&scope=channels:history channels:write channels:read chat:write:bot chat:write:user groups:history groups:read groups:write files:read files:write:user im:history im:read im:write search:read stars:read team:read users.profile:write users:read users:write&team=canopydigital&redirect_uri=https://yannickglt.github.io/alfred-slack/?client_id=‪‬5200166808.540275786487
```

encoded-url
```
https://slack.com/oauth/authorize?client_id=%E2%80%AA%E2%80%AC5200166808.540275786487&scope=channels%3Ahistory%20channels%3Awrite%20channels%3Aread%20chat%3Awrite%3Abot%20chat%3Awrite%3Auser%20groups%3Ahistory%20groups%3Aread%20groups%3Awrite%20files%3Aread%20files%3Awrite%3Auser%20im%3Ahistory%20im%3Aread%20im%3Awrite%20search%3Aread%20stars%3Aread%20team%3Aread%20users.profile%3Awrite%20users%3Aread%20users%3Awrite&team=canopydigital&redirect_uri=https%3A%2F%2Fyannickglt.github.io%2Falfred-slack%2F%3Fclient_id%3D%E2%80%AA%E2%80%AC5200166808.540275786487
```

**Comment by yannickglt** [comment]
After comparing to my own app client ID, I think I found why the client ID sounds invalid.

The encoded URL lets appear some invalid characters (which are not visible on the decoded URL but which are still present as they will appear again after URL encoding): client_id=**%E2%80%AA%E2%80%AC**5200166808.540275786487. If I'm right then, your client ID is `5200166808.540275786487`. 

I suggest you to try the same URL after removing the invalid chars and give it a new try:
```
https://slack.com/oauth/authorize?client_id=5200166808.540275786487&scope=channels:history%20channels:write%20channels:read%20chat:write:bot%20chat:write:user%20groups:history%20groups:read%20groups:write%20files:read%20files:write:user%20im:history%20im:read%20im:write%20search:read%20stars:read%20team:read%20users.profile:write%20users:read%20users:write&team=canopydigital&redirect_uri=https://yannickglt.github.io/alfred-slack/?client_id=5200166808.540275786487
```

Let me know if that solution works.

**Comment by an00bhav** [comment]
@yannickglt I have the same problem but the solution is not working for me. Any pointers?

**Comment by yannickglt** [comment]
You are on another client ID right? Can you paste the encoded URL please?

**Comment by an00bhav** [comment]
@yannickglt My bad, I did not save the redirect urls in my slack app settings. I got the token! 👍

**Comment by yannickglt** [comment]
OK thanks for reporting.
