### ISSUE TITLE
Can't add token

### ISSUE THREAD

**Issue by joshdeese** [yannickglt/alfred-slack#5]
After I add the workflow to alfred, I get my token. Then I open alfred type in slack and as soon as I type -- it tries to google search and doesn't give me an option to use the slack workflow anymore. Any suggestions?

**Comment by tamano** [comment]
Same thing happening to me after updating to 3e8b4131b313325dbcd6b9498f7b6404fbdd0aa2 .

**Comment by yannickglt** [comment]
It should be fixed with version 2.0.3.

**Comment by tamano** [comment]
@yannickglt 
Thanks for response. Have you identified the problem?
I've got error message below on debug window when I typed `slack -` .

https://gist.github.com/tamano/aa2f989b461b87f82f08

**Comment by yannickglt** [comment]
Thank you for your return @tamano! Could you check that you got the last version? If the problem is not solved, maybe you can force the cache refresh using `slack --refresh`.

**Comment by tamano** [comment]
Thank you for your suggestion!
I update Alfred from 2.8.0 to 2.8.1 and uninstall alfred-slack and re-install.
And now it getting work perfectly :+1:

**Comment by joshdeese** [comment]
Works for me now also. Thanks!
