### ISSUE TITLE
clarify permissions?

### ISSUE THREAD

**Issue by psifertex** [yannickglt/alfred-slack#52]
Given the reference to the URL to generate an ID it's not at all clear to me what permissions I'm giving a third-party to access my slack accounts if I follow these steps. Is the idea that I can run a separate dedicated instance myself? Or is the code generator unrelated to the main plugin that only runs locally and therefore no third-party can access anything?

**Comment by yannickglt** [comment]
You can definitely generate a token by yourself with the permissions you want. If some permissions are missing, some workflow features will just not work as expected. 
The generator URL just helps you to get a token with all necessary rights. 
You can see the permissions list [there](https://github.com/yannickglt/alfred-slack/blob/gh-pages/assets/script.js#L4) and globally look at the whole generator [source code](https://github.com/yannickglt/alfred-slack/blob/gh-pages).

**Comment by psifertex** [comment]
The second link appears to be 404, but I assume you mean https://github.com/yannickglt/alfred-slack/blob/master/src/public/assets/script.js ?

Thanks, that's very helpful, knowing I can just run my own server to generate the token is very helpful. When I work through it, I'd be happy to submit a PR for documentation in the README describing that alternate workflow if you're not against it.
