### ISSUE TITLE
Locked on refreshing cache

### ISSUE THREAD

**Issue by Chris-Nicol** [yannickglt/alfred-slack#9]
Hi,

First off ... wonderful workflow ... thank you!

Second ... I'm getting stuck in "Refresh still in progress". If I try to do anything I'll get that message. It's been that way for weeks, I've tried deleting the workflow and reinstalling it, but no dice.

Is there somewhere specific that the data is being stored that I can clean so I can get a fresh install of the workflow?

Thanks,
Chris

**Comment by yannickglt** [comment]
Hi,

Thank you for using Alfred Slack! The refresh process may take several minutes depending on the number of synchronized teams and their size.

Could you give me the [debug trace](https://www.alfredapp.com/blog/releases/alfred-v2-2-released-workflow-organisation-and-debugging/) of the workflow when you launch the refresh ?

You can remove all the workflow cache removing the workflow data folder as below:

``` bash
rm -rf ~/Library/Application\ Support/Alfred\ 2/Workflow\ Data/com.yannickglt.alfred2.slack
```

Thank you,

Yannick

**Comment by Chris-Nicol** [comment]
Hey Yannick,

I've definitely given it much more than the several minutes. The only message that comes through the debug window is below

Nothing else gets written to the debug window after pressing enter on a command. I'm going to clean out my workflow cache and try again, but I thought I'd grab the debug for you incase it was helpful, but it doesn't look like it's giving you much info.

Thanks,
Chirs

[STDERR: alfred.workflow.input.scriptfilter] ACTION: AlfredSlack\Controllers\ConfigController::listConfigsAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"listConfigs\",\"params\":{\"config\?\":\"\"}}";include "scripts/index.php";';
[STDERR: alfred.workflow.input.scriptfilter] ACTION: AlfredSlack\Controllers\ConfigController::listConfigsAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"listConfigs\",\"params\":{\"config\?\":\"res\"}}";include "scripts/index.php";';
[STDERR: alfred.workflow.input.scriptfilter] ACTION: AlfredSlack\Controllers\ConfigController::listConfigsAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"listConfigs\",\"params\":{\"config\?\":\"re\"}}";include "scripts/index.php";';
[STDERR: alfred.workflow.input.scriptfilter] ACTION: AlfredSlack\Controllers\ConfigController::listConfigsAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"listConfigs\",\"params\":{\"config\?\":\"ref\"}}";include "scripts/index.php";';
[STDERR: alfred.workflow.input.scriptfilter] ACTION: AlfredSlack\Controllers\ConfigController::listConfigsAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"listConfigs\",\"params\":{\"config\?\":\"refre\"}}";include "scripts/index.php";';
[STDERR: alfred.workflow.input.scriptfilter] ACTION: AlfredSlack\Controllers\ConfigController::listConfigsAction()
SIMULATE: php -r '$query="{\"controller\":\"config\",\"action\":\"listConfigs\",\"params\":{\"config\?\":\"refresh\"}}";include "scripts/index.php";';

**Comment by yannickglt** [comment]
Hi!
A new major version was released. It fixed some issues regarding the way to add clients. Your issue may be fixed as well if you want to give it a check.
